Update users.md
If you try and install using pip from within the geos directory, pip throws:
ERROR: file:///home/web/geos/geos does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
So the command to "cd geos" is wrong & should be removed.